_base_: proplogic.yaml

train:
  num_epochs: 1
  batch_size: 4

gradient:
  minibatch_size: 4
  merge_batch_size: 4
  analyst_workers: 2

optimizer:
  learning_rate: 2
  min_learning_rate: 2

env:
  limit: 6
